### ISSUE TITLE
aws-rag-appsync-stepfn-opensearch: minimum deployable pattern no longer works

### ISSUE THREAD

**Issue by davetbo-amzn** [awslabs/generative-ai-cdk-constructs#130]
### Describe the issue

The  README for the aws-rag-appsync-stepfn-opensearch pattern includes the following import:

`import { RagApiGatewayOpensearch, RagApiGatewayOpensearchProps } from '@cdklabs/generative-ai-cdk-constructs';`

However, you can see in lines 124-127 of the aws-rag-appsync-stepfn-opensearch/index.d.ts file that you've changed the name of the export. The comment references the old name and the export references thange from ApiGateway to AppSync.

```
/**
   * @summary The RagApiGatewayOpensearch class.
   */
export class RagAppsyncStepfnOpensearch extends Construct {
```

Please update the pattern README to reflect a working deployment.

Also, some customers may prefer API Gateway to AppSync due to familiarity, so maybe making both an option going forward would be best.

### Links

https://github.com/awslabs/generative-ai-cdk-constructs/blob/main/src/patterns/gen-ai/aws-rag-appsync-stepfn-opensearch/README.md

**Comment by krokoko** [comment]
Hi @davetbo-amzn , thank you for flagging this ! I will address it asap
