### ISSUE TITLE
(RAG/QA): OpenSearch Serverless support

### ISSUE THREAD

**Issue by krokoko** [awslabs/generative-ai-cdk-constructs#136]
### Describe the feature

OpenSearch Serverless support : currently the constructs support only a provisioned OpenSearch cluster

### Use Case

Reduction in complexity, autoscaling

### Acknowledgements

- [x] I may be able to implement this feature request
- [x] This feature might incur a breaking change

**Comment by hvital** [comment]
https://github.com/awslabs/generative-ai-cdk-constructs/pull/212

**Comment by krokoko** [comment]
PR merged, closing
