### ISSUE TITLE
(QA construct): Update Q/A logic

### ISSUE THREAD

**Issue by krokoko** [awslabs/generative-ai-cdk-constructs#137]
### Describe the feature

Currently, the https://github.com/awslabs/generative-ai-cdk-constructs/tree/main/src/patterns/gen-ai/aws-qa-appsync-opensearch construct's logic uses a long context window approach if a document name is specified. However, the end user might want to choose a RAG approach. 

### Use Case

Provide more flexibility to the end user

### Proposed Solution

Add a new parameter to the GraphQL schema to select the method

### Acknowledgements

- [x] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by MichaelWalker-git** [comment]
### Reiterating the problem 

The construct currently employs a long context window approach for document processing when a document name is specified. This means it likely uses the entirety of the document's content or a significant part of it as context for generating responses.

### Potential Solution

A potential solution involves adding a new parameter to the GraphQL schema that allows users to select the method (long context window or RAG). This parameter could be something like responseGenerationMethod with possible values longContext and RAG.

### Plan
1. Schema Update: Modify the GraphQL schema to include the new parameter.
2. Handling the Parameter in Lambda Functions: Update the AWS Lambda function logic to handle this new parameter. This will involve:
  - Implementing a conditional logic to choose between the long context window approach and the RAG approach based on the parameter's value.
  - For the RAG approach, you might need to implement or integrate a mechanism to fetch relevant document snippets based on the query, which are then used as context for the response generation.
4. Testing: Ensure thorough testing for both paths (long context and RAG) to confirm that the system behaves as expected in each case.
5. Update the documentation to include information about the new parameter, and provide examples of how to use it.

**Comment by krokoko** [comment]
Perfect, thanks @MichaelWalker-git ! Just one comment: "For the RAG approach, you might need to implement or integrate a mechanism to fetch relevant document snippets based on the query, which are then used as context for the response generation." -> this is already there, need only the conditional logic :)
