### ISSUE TITLE
(Constructs README): add Python code snippets

### ISSUE THREAD

**Issue by krokoko** [awslabs/generative-ai-cdk-constructs#141]
### Describe the issue

Each construct README provides a code snippet for Typescript (minimum deployable pattern definition), however there is no code snippet for Python

### Links

https://github.com/awslabs/generative-ai-cdk-constructs/tree/main/src/patterns/gen-ai -> every README

**Comment by martinezedgar** [comment]
Hi @krokoko, I would like to work on this issue.

**Comment by krokoko** [comment]
Hi @martinezedgar , thank you ! Sure, I will assign the ticket to yourself. 

2 main items for this ticket:
1) For python code snippets, you can add them to each readme file below the existing Typescript code snippet, something like:

Typescript
```
code snippet
```
Python
```
code snippet
```

2) Add python package to the existing table in each readme. It would look as follow:

| **Language**     | **Package**        |
|:-------------|-----------------|
|![Typescript Logo](https://docs.aws.amazon.com/cdk/api/latest/img/typescript32.png) Typescript|`@cdklabs/generative-ai-cdk-constructs`|
|![Python Logo](https://docs.aws.amazon.com/cdk/api/latest/img/python32.png) Python|`cdklabs.generative_ai_cdk_constructs`|

**Comment by martinezedgar** [comment]
Perfect, I will do it like that.

**Comment by krokoko** [comment]
Hi @martinezedgar , thanks ! I see you opened a PR, do you still have an issue with the ```HuggingFaceSageMakerEndpoint``` construct in Python ? Are you facing the same issue for the JumpStart version ? (I see the comment in your PR)

**Comment by martinezedgar** [comment]
Hi @krokoko, yes I am still having the same issues in HuggingFace and JumpStart but I included the preliminary snippets for both in their respective README files. The other snippets work just fine, do you have any idea about what is going on?

**Comment by krokoko** [comment]
I will have a look and try to reproduce

**Comment by krokoko** [comment]
Hi @martinezedgar I was able to reproduce, will investigate and provide an update here, thank you for reporting this issue !

**Comment by martinezedgar** [comment]
Thank you very much for your help @krokoko, let me know if there is anything I can help with.

**Comment by krokoko** [comment]
@martinezedgar I just opened a PR to address the issue (https://github.com/awslabs/generative-ai-cdk-constructs/pull/218), once it is merged you will be able to add the missing snippets

**Comment by martinezedgar** [comment]
Perfect, I'll wait.
