### ISSUE TITLE
(New construct): Image generation

### ISSUE THREAD

**Issue by krokoko** [awslabs/generative-ai-cdk-constructs#148]
### Describe the feature

Build a construct for image generation using Amazon Bedrock's Stable Diffusion XL
Backend only, a sample solution with a UI can then be built 

### Use Case

Expanding catalog

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by dineshSajwan** [comment]
#proposed solution.
1. A construct to generate the image based on text, add props to control the inference
2. guardrails with amazon comprehend on the prompt.
3. guardrails with aws rekognition on generated image.
4. store the generated image on s3
5
