### ISSUE TITLE
(All constructs): Evaluate Terraform support

### ISSUE THREAD

**Issue by krokoko** [awslabs/generative-ai-cdk-constructs#151]
### Describe the feature

Evaluate Terraform support for constructs

### Use Case

More flexibility for end user

### Acknowledgements

- [x] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by MichaelWalker-git** [comment]
Good starting points for links:

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/appsync_graphql_api

https://developer.hashicorp.com/terraform/cdktf

https://github.com/aws-samples/rag-using-langchain-amazon-bedrock-and-opensearch
