### ISSUE TITLE
(new construct): Implement Amazon Bedrock features as CDK constructs

### ISSUE THREAD

**Issue by krokoko** [awslabs/generative-ai-cdk-constructs#169]
### Describe the feature

Amazon Bedrock recently unveiled some features which are not available through CDK at the moment (Guardrails, knowledge bases, agents). 

### Use Case

Provide new features for end users

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by jstrunk** [comment]
Hi @krokoko ,

I implemented Constructs and custom resources for Knowledge Bases with AOSS and Data Sources and Agents with Agent versions in my last prototype. This week I will translate from Python to TypeScript.

Features

- Knowledge Base backed by an Amazon OpenSearch Serverless Collection
  - Configurable description, embeddings model, AOSS Collection, index name, and vector field.
  - Creates Vector Index in collection
  - Missing alternative vector stores
- KB Data Source
  - All options available in custom resource: https://docs.aws.amazon.com/bedrock/latest/APIReference/API_agent_CreateDataSource.html
-  Agent
  - All options available in custom resource: https://docs.aws.amazon.com/bedrock/latest/APIReference/API_agent_CreateAgent.html
  - Associates KBs with Agent and uses the KB description in the Agent.
  - Creates an Agent Alias with a configurable name. Default is "prod"
  - Any change to KB, Data Source, or Agent creates a new Alias
- IAM and AOSS policies defined for least privilege.

Missing functionality
- Other vector stores for KB
- Agent Action groups

**Comment by jstrunk** [comment]
I will put these constructs in common. I'm not sure it makes sense to put them in helpers, but they could go there.

I propose putting these constructs in common/bedrock and the opensearch serverless vector constructs in helpers.

**Comment by dineshSajwan** [comment]
Thank you @jstrunk , this is really helpful. yes you can add opensearch serverless vector constructs in common/helpers and put KB and Agent constructs in src/cdk-lib/gen-ai.
