### ISSUE TITLE
(gen-ai): JumpStartSageMakerEndpoint not working

### ISSUE THREAD

**Issue by LeonLuttenberger** [awslabs/generative-ai-cdk-constructs#179]
### Describe the bug

I'm unable to deploy the SageMaker endpoint using the `JumpStartSageMakerEndpoint` construct.

### Expected Behavior

The endpoint gets created.

### Current Behavior

CloudFormation throws the following error when trying to create the endpoint:
```
Could not find model data at s3://jumpstart-cache-prod-us-east-1/huggingface-asr/huggingface-asr-whisper-base/artifacts/inference-prepack/v1.0.1/. (Service: AmazonSageMaker; Status Code: 400; Error Code: ValidationException; Request ID: 8e830934-e61a-4c1e-96e5-1663211204b0; Proxy: null)
```

![error](https://github.com/awslabs/generative-ai-cdk-constructs/assets/15194249/5ddce0de-b044-4f79-bbf0-250ef7957b16)

### Reproduction Steps

```typescript
import * as cdk from "aws-cdk-lib";
import { Construct } from "constructs";
import {
  JumpStartModel,
  SageMakerInstanceType,
  JumpStartSageMakerEndpoint,
} from "@cdklabs/generative-ai-cdk-constructs";

export class SagemakerJumpStartFmEndpointStack extends cdk.Stack {
  jumpStartEndpoint: JumpStartSageMakerEndpoint;

  constructor(scope: Construct, id: string, props: SagemakerJumpStartFmEndpointStackProps) {
    super(scope, id, props);

    this.jumpStartEndpoint = new JumpStartSageMakerEndpoint(this, "JumpStartEndpoint", {
      model: JumpStartModel.HUGGINGFACE_ASR_WHISPER_BASE_2_0_0,
      instanceType: SageMakerInstanceType.of("ml.g5.2xlarge"),
    });
}
```

### CDK CLI Version

2.111.0

### Framework Version

0.1.11

### Node.js Version

21.4.0

### OS

Mac OS

### Language

Typescript

### Region experiencing the issue

us-east-1

### Code modification

No

### Service quota

- [X] I have reviewed the service quotas for this construct

**Comment by krokoko** [comment]
Hi @LeonLuttenberger, thank you for reporting this ! I was able to reproduce

**Issue**:
The construct is expecting to get the model artifacts as a single gzip compressed tar archive (.tar.gz suffix)
However, for some models, it is not the case. It seems to affect all models in version 2_0_0 or above.

The construct needs to handle this edge case
