### ISSUE TITLE
aws-qa-appsync-opensearch: Index not found

### ISSUE THREAD

**Issue by mmuller88** [awslabs/generative-ai-cdk-constructs#248]
### Describe the bug

I'm using the `QaAppsyncOpensearch` construct (https://github.com/awslabs/generative-ai-cdk-constructs/tree/main/src/patterns/gen-ai/aws-qa-appsync-opensearch) with a new created OpenSearch. The Lambda logs keep complaining about not can find the index. But as of my understanding the index should be created automatically when it can't be found.

```
[ERROR] NotFoundError: NotFoundError(404, 'index_not_found_exception', 'no such index', demoindex, index_or_alias)
Traceback (most recent call last):
```

I'm adding OpenSearch like that:

```
      const osDomain = new os.Domain(stack, "Domain", {
        version: os.EngineVersion.ELASTICSEARCH_2_3,
        capacity: {
          masterNodeInstanceType: "t2.micro.search",
          dataNodeInstanceType: "t2.micro.search",
        },
        removalPolicy: cdk.RemovalPolicy.DESTROY,
      });
 ```

### Expected Behavior

AppSync request is successful

### Current Behavior

AppSync keeps on status "Working on the question"

### Reproduction Steps

Create a simple CDK deployment like that and run the AppSync subscription and mutation

```
      const osDomain = new os.Domain(stack, "Domain", {
        version: os.EngineVersion.ELASTICSEARCH_2_3,
        capacity: {
          masterNodeInstanceType: "t2.micro.search",
          dataNodeInstanceType: "t2.micro.search",
        },
        removalPolicy: cdk.RemovalPolicy.DESTROY,
      });

      const rag_source = new QaAppsyncOpensearch(this, "QaAppsyncOpensearch", {
        existingOpensearchDomain: osDomain,
        openSearchIndexName: 'demoindex',
        cognitoUserPool: cognito.cdk.userPool,
      });
      rag_source.s3InputAssetsBucket?.applyRemovalPolicy(
        cdk.RemovalPolicy.DESTROY
      );
```

### Possible Solution

Maybe my OpenSearch is to low tier?

### CDK CLI Version

2.124.0

### Node.js Version

20

### OS

mac

### Language

Typescript

### Region experiencing the issue

us-east-1

### Code modification

..

### Service quota

- [X] I have reviewed the service quotas for this construct

**Comment by krokoko** [comment]
Hi @mmuller88 ,

If you use only the ```QaAppsyncOpensearch``` construct, then you need to ingest the documents into the OpenSearch instance on your own. This construct expects you to provide a vector DB which already contains an index.

Another construct ((aws-rag-appsync-stepfn-opensearch)[https://github.com/awslabs/generative-ai-cdk-constructs/tree/main/src/patterns/gen-ai/aws-rag-appsync-stepfn-opensearch]) is available and provides an ingestion pipeline. You can upload PDF documents into an Amazon S3 bucket, and trigger the ingestion process which will create and store the embeddings in the vector DB. Here, the index is created if it doesn't exist.

You can compose both constructs together to create a Q/A with RAG workflow (share the OpenSearch instance between both constructs)

An example of both constructs used together is available in our [samples repo](https://github.com/aws-samples/generative-ai-cdk-constructs-samples/tree/main/samples/document_explorer)

**Comment by krokoko** [comment]
Closing the issue, please reopen if you have any other question. Thank you !

**Comment by mmuller88** [comment]
@krokoko thanks a lot :). This lib is pretty awesome. Kind of super interesting how AppSync is used to kind of push the AI interface more into the backend. I'm setting up a nextjs app which can answer questions about Meetup events from the past. So far it pretty works great.
