### ISSUE TITLE
(Bedrock/Agents): helper methods to associate KnowledgeBases to Agents

### ISSUE THREAD

**Issue by massi-ang** [awslabs/generative-ai-cdk-constructs#270]
### Describe the feature

Allow for adding a KnowledgeBase to an agent and not only to specify existing KBs at the agent construct instantiation.

### Use Case

Allow for more flexibility in the order in which agents and KBs are created

### Proposed Solution

Implement a `Agent.addKnowldgeBase(KnowledgeBase, {instructions})` and a `KnowledgeBase.assToAgent(Agent, {instruxtions})` methods

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by aws-rafams** [comment]
working on it

**Comment by krokoko** [comment]
Thanks for updating the ticket @aws-rafams !
