### ISSUE TITLE
(bedrock): add other stores

### ISSUE THREAD

**Issue by moltar** [awslabs/generative-ai-cdk-constructs#279]
### Describe the feature

I'd like to be able to use stores other than Amazon OpenSearch Serverless.

### Use Case

Amazon OpenSearch Serverless is riding on serverless fame or low costs, yet it's one of the most ridiculously priced services.

The minimal cost of running an Amazon OpenSearch Serverless index is ~ $700/mo.

Source:

- https://repost.aws/questions/QUAc9Mg6avRCy3e5kOF8v5fQ/pricing-strategy-for-open-search-serverless
- https://repost.aws/questions/QUPxlXCMbVSdqLvCqQcW-lMw/clarification-on-opensearch-serverless-pricing

### Proposed Solution

Provide options for other storage backends that are more reasonably priced.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by krokoko** [comment]
Hi @moltar , thank you for reporting this feature request ! From the [official FAQ](https://aws.amazon.com/bedrock/faqs/#:~:text=Knowledge%20Bases%20for%20Amazon%20Bedrock%20supports%20popular%20databases%20for%20vector,and%20MongoDB%20(coming%20soon).), Knowledge Bases for Amazon Bedrock supports Amazon OpenSearch Serverless, Pinecone, Redis Enterprise Cloud, Amazon Aurora (coming soon), and MongoDB (coming soon). We will have a look at the 2 other options available now (Pinecone, Redis Enterprise Cloud)

**Comment by dwright20** [comment]
Think the FAQ might be outdated. This article was posted on Feb 2nd and describes how to use Amazon Aurora: https://aws.amazon.com/blogs/database/build-generative-ai-applications-with-amazon-aurora-and-knowledge-bases-for-amazon-bedrock/. Awesome constructs! +1 on adding Amazon Aurora support
