### ISSUE TITLE
(sagemaker-model-deployment): Support AWS Inferentia instance types

### ISSUE THREAD

**Issue by kukushking** [awslabs/generative-ai-cdk-constructs#290]
### Describe the feature

I'd like to be able to use AWS Inferentia for my endpoint inference containers

### Use Case

-

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by krokoko** [comment]
Hi @kukushking , we do have 2 samples demonstrating how to deploy models on Inferentia : 
- https://github.com/aws-samples/generative-ai-cdk-constructs-samples/tree/main/samples/sagemaker_huggingface_inferentia 
- https://github.com/aws-samples/generative-ai-cdk-constructs-samples/tree/main/samples/sagemaker_custom_endpoint

Is there a model in particular you are looking to deploy ?

**Comment by kukushking** [comment]
Thanks @krokoko. Is this supported for JumpStart Foundation Models? I don't see Inf instance types [here](https://github.com/awslabs/generative-ai-cdk-constructs/blob/main/src/patterns/gen-ai/aws-model-deployment-sagemaker/sagemaker-instance-type.ts)

**Comment by kukushking** [comment]
Ah sorry just found it. Nvm, closing the issue.

**Comment by kukushking** [comment]
`Error: The instance type ml.inf1.2xlarge is not supported. Default instance type: ml.g5.2xlarge. Supported instance types: ml.g5.2xlarge, ml.g5.4xlarge, ml.g5.8xlarge, ml.g5.16xlarge.`

I get this error when deploying Mistral 7B with Inf. Am I doing something wrong?

**Comment by krokoko** [comment]
Could you please share the code snippet you are using ?

**Comment by kukushking** [comment]
Sure, [here](https://github.com/awslabs/mlops-modules/blob/main/modules/fmops/sagemaker-jumpstart-fm-endpoint/lib/sagemaker-jumpstart-fm-endpoint-stack.ts#L90) is the link.

**Comment by krokoko** [comment]
Thanks @kukushking , do you have the specific model that is not working for you ?
