### ISSUE TITLE
(bedrock): adopt official cloudformation resources

### ISSUE THREAD

**Issue by jstrunk** [awslabs/generative-ai-cdk-constructs#361]
### Describe the feature

The Amazon Bedrock team recently released CloudFormation support. https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-bedrock-agent.html

### Use Case

We can remove the bedrock custom resources.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [X] This feature might incur a breaking change

**Comment by krokoko** [comment]
Thank you @jstrunk , we will add it to the backlog

**Comment by jlosito** [comment]
It looks like this relates to https://github.com/aws/aws-cdk/issues/29858
