### ISSUE TITLE
amazonaurora: ImportError: cannot import name 'AmazonAuroraDefaultVectorStore'

### ISSUE THREAD

**Issue by eercanayar** [awslabs/generative-ai-cdk-constructs#365]
### Describe the bug

`cdklabs.generative-ai-cdk-constructs 0.1.107` doesn't import properly with a vanilla setup. Please check the details provided below.

### Expected Behavior

- To import the library correctly
- To avoid being impacted by issues or errors from other modules when importing a module (I was trying to use `opensearch_vectorindex` but impacted by `amazonaurora`.)
- A build pipeline test to catch these type of breaking errors to avoid broken version releases.

### Current Behavior

```
$ cdk synth                                                      
Traceback (most recent call last):
  File "/Users/***/Experimental/aoss-experiment/app.py", line 6, in <module>
    from aoss_experiment.aoss_experiment_stack import AossExperimentStack
  File "/Users/***/Experimental/aoss-experiment/aoss_experiment/aoss_experiment_stack.py", line 7, in <module>
    from cdklabs.generative_ai_cdk_constructs import (
  File "/Users/***/Experimental/aoss-experiment/.venv/lib/python3.10/site-packages/cdklabs/generative_ai_cdk_constructs/__init__.py", line 21232, in <module>
    from . import amazonaurora
  File "/Users/***/Experimental/aoss-experiment/.venv/lib/python3.10/site-packages/cdklabs/generative_ai_cdk_constructs/amazonaurora/__init__.py", line 79, in <module>
    from ..bedrock import BedrockFoundationModel as _BedrockFoundationModel_91d045a3
  File "/Users/***/Experimental/aoss-experiment/.venv/lib/python3.10/site-packages/cdklabs/generative_ai_cdk_constructs/bedrock/__init__.py", line 348, in <module>
    from ..amazonaurora import (
ImportError: cannot import name 'AmazonAuroraDefaultVectorStore' from partially initialized module 'cdklabs.generative_ai_cdk_constructs.amazonaurora' (most likely due to a circular import) (/Users/***/Experimental/aoss-experiment/.venv/lib/python3.10/site-packages/cdklabs/generative_ai_cdk_constructs/amazonaurora/__init__.py)
```

### Reproduction Steps

Run: 
```
cdk init --language python
source .venv/bin/activate
echo "cdklabs.generative-ai-cdk-constructs" >> requirements.txt
```

In the stack file, import the library:
```python
from cdklabs.generative_ai_cdk_constructs import (
    opensearchserverless,
    opensearch_vectorindex,
)
```

Run `cdk synth` and observe the error.

### Additional Information/Context

```
$ pip freeze
attrs==23.2.0
aws-cdk-lib==2.126.0
aws-cdk.asset-awscli-v1==2.2.202
aws-cdk.asset-kubectl-v20==2.1.2
aws-cdk.asset-node-proxy-agent-v6==2.0.3
cattrs==23.2.3
cdk-nag==2.28.84
cdklabs.generative-ai-cdk-constructs==0.1.107
constructs==10.3.0
exceptiongroup==1.2.0
importlib_resources==6.4.0
jsii==1.96.0
publication==0.0.3
python-dateutil==2.9.0.post0
six==1.16.0
typeguard==2.13.3
typing_extensions==4.11.0
```

### CDK CLI Version

2.126.0 (build fb74c41)

### Node.js Version

v21.0.0

### OS

macOS 14.3.1

### Language

Python

### Language Version

Python 3.10.13

### Region experiencing the issue

non-related

### Code modification

None

### Service quota

- [X] I have reviewed the service quotas for this construct

**Comment by eercanayar** [comment]
Additional analysis:
I tried and `cdklabs.generative-ai-cdk-constructs==0.1.106` doesn't have this issue. We may want to focus changes between 106 and 107 to understand and resolve this.

**Comment by krokoko** [comment]
Thank you for reporting this issue @eercanayar , I was able to reproduce. Will update this ticket when a fix is available
