### ISSUE TITLE
Foundation Models are erring with Knowledge Base

### ISSUE THREAD

**Issue by smislam** [awslabs/generative-ai-cdk-constructs#375]
### Describe the bug

The default Foundation models are throwing errors when passed into the Knowledge Base.

### Expected Behavior

Default Foundation Models works with Knowledge base

### Current Behavior

I get the following error:

`@cdklabs\generative-ai-cdk-constructs\src\cdk-lib\bedrock\know
ledge-base.ts:610
    throw new Error(`The model ${foundationModel} is not supported by Bedrock Knowledge Base.`);
          ^
Error: The model amazon.titan-text-express-v1 is not supported by Bedrock Knowledge Base.`

### Reproduction Steps

use any of the Supported Foundation models in Knowledge Base.

### CDK CLI Version

2.137.0 (build bb90b4c)

### Framework Version

"@cdklabs/generative-ai-cdk-constructs": "^0.1.112"

### Node.js Version

v20.10.0

### OS

Windows

### Language

Typescript

### Region experiencing the issue

us-east-1

### Code modification

Unknown

### Service quota

- [X] I have reviewed the service quotas for this construct

**Comment by krokoko** [comment]
Hello @smislam , the model you mentioned is not available for knowledge bases. At the time of this comment, you can select among the following foundation models:
- TITAN_EMBED_TEXT_V1
- COHERE_EMBED_ENGLISH_V3
- COHERE_EMBED_MULTILINGUAL_V3
Closing the thread, please let me know if you have any additional question

**Comment by smislam** [comment]
Looks like I need to use specific models as documented here.   It works for me.

https://docs.aws.amazon.com/bedrock/latest/userguide/knowledge-base-supported.html
