### ISSUE TITLE
(bedrock): (sth wrong with agent.add_alias)

### ISSUE THREAD

**Issue by iut62elec** [awslabs/generative-ai-cdk-constructs#428]
### Describe the issue

 agent.add_alias(self, 'ProdAlias', 
            alias_name='prod',
            agent_version='1'
            )

What's Next?
  View a summary of image vulnerabilities and recommendations → docker scout quickview
520a336da5ec9de042a2fe58ced714507e77672438336c1fce319e6b2e3259c8
Traceback (most recent call last):
  File "/Users/jpedram/Pedram_work/Gen_AI/ookla_sql/text-to-sql-cdk/cdk/app.py", line 187, in <module>
    MyStack(app, "MyStack")
  File "/Users/jpedram/Pedram_work/Gen_AI/ookla_sql/text-to-sql-cdk/.venv/lib/python3.11/site-packages/jsii/_runtime.py", line 118, in __call__
    inst = super(JSIIMeta, cast(JSIIMeta, cls)).__call__(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jpedram/Pedram_work/Gen_AI/ookla_sql/text-to-sql-cdk/cdk/app.py", line 139, in __init__
    agent.add_alias(self, 'ProdAlias',
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: Agent.add_alias() takes 1 positional argument but 3 positional arguments (and 2 keyword-only arguments) were given

Subprocess exited with error 1
(.venv) ➜  cdk  
            
            
            

### Links

https://github.com/awslabs/generative-ai-cdk-constructs/tree/main/src/cdk-lib/bedrock#:~:text=%7D)%3B-,Python,-agent.add_alias

**Comment by krokoko** [comment]
Hi @iut62elec , thank you for reporting this issue, I was able to reproduce, will update this ticket when a fix is available
