### ISSUE TITLE
(bedrock): bedrock.ChunkingStrategy.DEFAULT doesn't deploy

### ISSUE THREAD

**Issue by InitialXW** [awslabs/generative-ai-cdk-constructs#476]
### Describe the bug

using version 0.1.157, deploying bedrock datasource returns error: Resource handler returned message: "Cannot invoke "software.amazon.bedrock.datasource.ChunkingConfiguration.getChunkingStrategy()" because "modelChunkingConfiguration" is null"

### Expected Behavior

deploy successful

### Current Behavior

returns error complaining no ChunkingConfiguration

### Reproduction Steps

 this.dataSource = new bedrock.S3DataSource(this, 'DataSource', {
      bucket: this.knowledgeBaseBucket,
      knowledgeBase: this.knowledgeBase,
      dataSourceName: 'mydatasource',
      chunkingStrategy: bedrock.ChunkingStrategy.DEFAULT,
      maxTokens: 1000,
      overlapPercentage: 10,
    });

### CDK CLI Version

2.139.0 (build 2699ffd)

### Node.js Version

v20.12.2

### OS

Linux

### Language

Typescript

### Region experiencing the issue

us-west-2

### Code modification

no

### Service quota

- [X] I have reviewed the service quotas for this construct

**Comment by krokoko** [comment]
Hi @InitialXW , thank you for reporting this. I will try to reproduce, in the meantime could you please try to change your chunkingStrategy to bedrock.ChunkingStrategy.FIXED_SIZE ?

**Comment by smislam** [comment]
I am also having the same issue with `"@aws-sdk/client-bedrock": "^3.552.0"`.  Can we please fix this?

For now, the following worked for me:

```
        chunkingStrategy: ChunkingStrategy.FIXED_SIZE,
        maxTokens: 300,
        overlapPercentage: 20
```

**Comment by krokoko** [comment]
Hi, thank you for reporting this issue, I was able to reproduce and will update this ticket when a fix is available
