### ISSUE TITLE
generative_ai_cdk_constructs: python cdk deploy failed with error unrecognized resource types

### ISSUE THREAD

**Issue by bttong** [awslabs/generative-ai-cdk-constructs#559]
### Describe the bug

cdk synth finished successfully but cdk deploy failed with the following error:
Deployment failed: Error [ValidationError]: Template format error: Unrecognized resource types: [AWS::OpenSearchServerless::AccessPolicy, AWS::Bedrock::DataSource, AWS::OpenSearchServerless::Collection, AWS::Bedrock::KnowledgeBase, AWS::OpenSearchServerless::SecurityPolicy]
    at Request.extractError (/Users/tongbrit/.nvm/versions/node/v20.11.0/lib/node_modules/aws-cdk/lib/index.js:405:46723)
    at Request.callListeners (/Users/tongbrit/.nvm/versions/node/v20.11.0/lib/node_modules/aws-cdk/lib/index.js:405:91777)
    at Request.emit (/Users/tongbrit/.nvm/versions/node/v20.11.0/lib/node_modules/aws-cdk/lib/index.js:405:91225)
    at Request.emit (/Users/tongbrit/.nvm/versions/node/v20.11.0/lib/node_modules/aws-cdk/lib/index.js:405:199828)
    at Request.transition (/Users/tongbrit/.nvm/versions/node/v20.11.0/lib/node_modules/aws-cdk/lib/index.js:405:193380)
    at AcceptorStateMachine.runTo (/Users/tongbrit/.nvm/versions/node/v20.11.0/lib/node_modules/aws-cdk/lib/index.js:405:158252)
    at /Users/tongbrit/.nvm/versions/node/v20.11.0/lib/node_modules/aws-cdk/lib/index.js:405:158582
    at Request.<anonymous> (/Users/tongbrit/.nvm/versions/node/v20.11.0/lib/node_modules/aws-cdk/lib/index.js:405:193672)
    at Request.<anonymous> (/Users/tongbrit/.nvm/versions/node/v20.11.0/lib/node_modules/aws-cdk/lib/index.js:405:199903)
    at Request.callListeners (/Users/tongbrit/.nvm/versions/node/v20.11.0/lib/node_modules/aws-cdk/lib/index.js:405:91945) {
  code: 'ValidationError',
  time: 2024-07-15T00:01:20.742Z,
  requestId: '419ae033-1f90-4892-a461-7fc12551e67d',
  statusCode: 400,
  retryable: false,
  retryDelay: 148.67063581860052
}

### Expected Behavior

Be able to deploy Bedrock Knowledge base resource

### Current Behavior

Refer to description

### Reproduction Steps

The following python code is used to configure knowledge based in cdk stack:

# Configure Bedrock knowledge base
        sa_review_knowledge_base = bedrock.KnowledgeBase(
            self,
            "sa-review-knowledge-base",
            embeddings_model=bedrock.BedrockFoundationModel.TITAN_EMBED_TEXT_V1,
            instruction="Use this knowledge base to answer review solution architects. ",
        )
        # Configure knowledge base datasource
        bedrock.S3DataSource(
            self,
            "sa-review-data-source",
            bucket=sa_review_bucket,
            knowledge_base=sa_review_knowledge_base,
            data_source_name="books",
            chunking_strategy=bedrock.ChunkingStrategy.FIXED_SIZE,
            max_tokens=1000,
            overlap_percentage=20,
        )

### CDK CLI Version

2.149.0

### Node.js Version

v20.11.0

### OS

MacOS

### Language

Python

### Region experiencing the issue

us-west-2

### Code modification

No

### Service quota

- [X] I have reviewed the service quotas for this construct

**Comment by krokoko** [comment]
Hi @bttong , thank you for reporting this issue ! Are you using the latest version of the constructs library? I am not able to reproduce the issue. Using the following code snippet:

```
kb = bedrock.KnowledgeBase(self, 'KnowledgeBase-OS', 
            embeddings_model= bedrock.BedrockFoundationModel.TITAN_EMBED_TEXT_V1,
            instruction=  'Use this knowledge base to answer questions about books. ' +
            'It contains the full text of novels.' ,
            description= 'This knowledge base contains the full text of novels.',                    
        )

        docBucket = s3.Bucket(self, 'DockBucket-OS')

        dataSource = bedrock.S3DataSource(self, 'DataSource-OS',
            bucket= docBucket,
            knowledge_base=kb,
            data_source_name='books',
            chunking_strategy= bedrock.ChunkingStrategy.FIXED_SIZE,
            max_tokens=100,
            overlap_percentage=20   
        ) 
```

The stack id deploying successfully (tested multiple times in us-east-1 and us-west-2)

**Comment by bttong** [comment]
Thank you @krokoko for looking into this. If you are talking about generative_ai_cdk_constructs then yes since I've just installed it couple days ago. Please note that the cdk synth works. The error above showed up when I did cdk deploy.

**Comment by krokoko** [comment]
Thanks @bttong , if you have the bandwidth could you please push your stack to a repo and link it here ? Since I am not able to reproduce it would be helpful. Thank you !

**Comment by bttong** [comment]
I've found the issue. I have to update the construct library in requirements.txt to something like `constructs>=10.0.0,<11.0.0` and the issue is resolved. The original requirement does not have version. It's related to the question you had earlier about the contructs. Thank you for your help.
