### ISSUE TITLE
(Bedrock agent): fail deployment when no guardrail is specified

### ISSUE THREAD

**Issue by krokoko** [awslabs/generative-ai-cdk-constructs#578]
### Describe the bug

Customer reached out mentioning that the deployment fails with ```'guardrailIdentifier' cannot be null```, because the guardrailConfiguration object is being set even when no guardrail is defined

### Expected Behavior

stack deploys correctly

### Current Behavior

stack fails to deploy

### Reproduction Steps

create an agent and don't provide guardrails configuration

### CDK CLI Version

2.143

### Node.js Version

20

### OS

MacOs

### Language

Typescript

### Region experiencing the issue

all

### Code modification

no

### Service quota

- [X] I have reviewed the service quotas for this construct

**Comment by aquark** [comment]
Here's how I define the agent in CDK:

```
    const bedrockAgent = new bedrock.Agent(this, "TaskeiAgent", {
      foundationModel:
        bedrock.BedrockFoundationModel.ANTHROPIC_CLAUDE_SONNET_V1_0,
      instruction: agentInstructions,
      enableUserInput: true,
      shouldPrepareAgent: true,
      name: "TaskeiAgent",
      description: "Agent used by the Taskei website",
    });
```

The error message returned by CloudFormation was:

```
Resource handler returned message: "'guardrailIdentifier' cannot be null (Service: BedrockAgent, Status Code: 400, Request ID: 2bdcd93c-805c-43c7-8ba8-ffac83ef3873)" (RequestToken: 054a40dc-4c9c-8bcb-d366-c82cbefd935b, HandlerErrorCode: InvalidRequest)
```

**Comment by krokoko** [comment]
Thanks @aquark , I was able to reproduce and working on a fix now, will update this ticket when done
