### ISSUE TITLE
(bedrock): bedrock.ChunkingStrategy.SEMANTIC is not implemented

### ISSUE THREAD

**Issue by grrapport** [awslabs/generative-ai-cdk-constructs#587]
### Describe the feature

Add support for ChunkingStrategy SEMANTIC as described [here](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-bedrock-datasource-chunkingconfiguration.html)

### Use Case

I want to use the SEMANTIC chunking strategy for a KnowledgeBase

### Proposed Solution

Add value for SEMANTIC to relevant files.

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by krokoko** [comment]
Hi @grrapport , thank you for this feature request ! I just started testing the 2 new chunking strategies, however when you try to deploy a template with either SEMANTIC or HIERARCHICAL you get an error like: 'HIERARCHICAL is not a valid enum value'. I will verify with the CloudFormation team if this is a bug and update this ticket accordingly.

**Comment by grrapport** [comment]
Thank you, I was tinkering with it on my side too and having some problems with CFN as well.

**Comment by krokoko** [comment]
Hi @grrapport , I heard back from the team and this is an error in the documentation. Those new chunking strategies are not supported yet in CloudFormation. I will close this ticket and re-open it when the feature is available to link it to the PR.

**Comment by aws-rafams** [comment]
CDK support landed in 2.154.0: https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_bedrock.CfnDataSource.html

**Comment by krokoko** [comment]
Great timing ! Reopening as available in the CDK now, will work on it

**Comment by krokoko** [comment]
This new feature requires the library to be updated to cdk v2.154.0, however I just found out that there is a bug in that version (see here: https://github.com/aws/aws-cdk/issues/31183) which currently prevents the upgrade. The library won't build as a property was removed in cfnDataSource. Will need to wait for V2.154.X for the fix

**Comment by krokoko** [comment]
A new version with the bug fixed was released overnight, will resume work on this asap

**Comment by vaughngit** [comment]
Thank you for the updates!

**Comment by krokoko** [comment]
Closed with [#668](https://github.com/awslabs/generative-ai-cdk-constructs/pull/668)
