### ISSUE TITLE
(aws-rag-appsync-stepfn-opensearch): CRUD operations on documents

### ISSUE THREAD

**Issue by krokoko** [awslabs/generative-ai-cdk-constructs#624]
### Describe the feature

As of today, users can only ingest documents and create embeddings. There is no CRUD operations to update or delete existing documents. The only way a user can update or remove embeddings is by deleting the OSS instance, and re-deploying one. 

### Use Case

Users have to destroy/re-deploy their stack if they want to update their embeddings

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by scottschreckengaust** [comment]
https://github.com/awslabs/generative-ai-cdk-constructs/issues/443
