### ISSUE TITLE
feat(models): (memory support)

### ISSUE THREAD

**Issue by aws-rafams** [awslabs/generative-ai-cdk-constructs#639]
### Describe the feature

Start implementing the Memory for Agents feature (currently in preview).

Memory provides your agent the ability to retain conversational context across multiple sessions and to recall past actions and behaviors. 
https://docs.aws.amazon.com/bedrock/latest/userguide/agents-memory.html 

### Use Case

You can access the memory at any time to view the summarized version of the sessions that are stored in the memory. You can also, at any time, clear the memory by deleting all the sessions stored in the memory.

### Proposed Solution

See PR

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by krokoko** [comment]
Closing following comments in https://github.com/awslabs/generative-ai-cdk-constructs/pull/640 , will reopen once the feature is available in L1 constructs
