### ISSUE TITLE
(bedrock): support additional data sources

### ISSUE THREAD

**Issue by krokoko** [awslabs/generative-ai-cdk-constructs#655]
### Describe the feature

New data sources config are available in cdk v2.154.1
https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_bedrock.CfnDataSource.DataSourceConfigurationProperty.html 

### Use Case

Missing features

### Acknowledgements

- [X] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by aws-rafams** [comment]
Can work on it

**Comment by krokoko** [comment]
Thanks @aws-rafams , sure, thanks ! Can I assign you the ticket ?

**Comment by aws-rafams** [comment]
> Thanks @aws-rafams , sure, thanks ! Can I assign you the ticket ?

Sure!

**Comment by krokoko** [comment]
Thanks @aws-rafams !

**Comment by krokoko** [comment]
This might be implemented at the same time: https://github.com/awslabs/generative-ai-cdk-constructs/issues/587 
Since chunking strategies update will impact the work on data sources

**Comment by aws-rafams** [comment]
> This might be implemented at the same time: #587 Since chunking strategies update will impact the work on data sources

Yes, I actually already have some work done, only with that part missing and the whole testing part. Can take care of it as well :)
