### ISSUE TITLE
(OpenSearch): Metadata Field property not changed to filterable false

### ISSUE THREAD

**Issue by naerolf** [awslabs/generative-ai-cdk-constructs#680]
### Describe the bug

When creating through CDK the OpenSearch index, assigning a metadata field to be non filterable in the code is not respected in the final deployment in console

### Expected Behavior

When assigning a metadata field in OpenSearch through the construct deployment, to have the filterable field false as stated in the deployment code.

### Current Behavior

When declaring in the sample `AMAZON_BEDROCK_METADATA` field, is expected to be not filterable through Knowledge Base metadata filters. Currently what happens is if we declare it false, the deployment automatically sets it to true as shown in the screenshot.

![cdk_opensearch_issue](https://github.com/user-attachments/assets/26da2673-2423-4df2-8cbc-5156a72454db)

### Reproduction Steps

```
vector_index = VectorIndex(self, config['OPENSEARCH_SERVERLESS']['vector_index_name'].lower(),
                                   vector_dimensions=1536,
                                   collection=vector_collection,
                                   index_name=config['OPENSEARCH_SERVERLESS']['vector_index_name'].lower(),
                                   vector_field=config['OPENSEARCH_SERVERLESS']['vector_field_name'].lower(),
                                   mappings=[
                                       MetadataManagementFieldProps(
                                           mapping_field='AMAZON_BEDROCK_TEXT_CHUNK',
                                           data_type='text',
                                           filterable=True
                                       ),
                                       MetadataManagementFieldProps(
                                           mapping_field='AMAZON_BEDROCK_METADATA',
                                           data_type='text',
                                           filterable=False
                                       )
                                   ]
                                   )
```

### CDK CLI Version

2.155.0

### Framework Version

build 34dcc5a

### Node.js Version

Node 18

### OS

Mac OS 14.5 (23F79)

### Language

Python

### Region experiencing the issue

us-east-1

### Code modification

No, it does not apply for the current issue.

### Service quota

- [X] I have reviewed the service quotas for this construct

**Comment by krokoko** [comment]
Hi @naerolf thank you for reporting this issue ! I will try to reproduce

**Comment by krokoko** [comment]
This is reproducible:

![image](https://github.com/user-attachments/assets/9249030a-a874-42f1-a735-346aba03e7a5)

However when created through a KB, mapping is correct:

![image](https://github.com/user-attachments/assets/dbdbd968-fe67-4294-838c-2cac58bf50eb)
