### ISSUE TITLE
@cdklabs/generative-ai-cdk-constructs: CDK considers a subsequent deploy of a knowledge base as a creation of a new knowledge base even though it is a simple NPM package upgrade

### ISSUE THREAD

**Issue by malikalimoekhamedov** [awslabs/generative-ai-cdk-constructs#690]
### Describe the bug

I have a Bedrock knowledge base I construct with CDK like so:

```typescript
const vectorStore = new opensearchserverless.VectorCollection(
  this,
  'VectorCollectionName',
  {
    collectionName: 'collection-name',
    standbyReplicas:
      process.env.ENV === 'prd'
        ? opensearchserverless.VectorCollectionStandbyReplicas.ENABLED
        : opensearchserverless.VectorCollectionStandbyReplicas.DISABLED,
  }
);

new bedrock.KnowledgeBase(this, 'MyKnowledgeBaseName', {
  embeddingsModel: bedrock.BedrockFoundationModel.TITAN_EMBED_TEXT_V2_1024,
  instruction: 'Some instructions.',
  description: 'Knowledge base description.',
  vectorStore,
});
```

Without changing anything to this setting and simply upgrading to the latest npm package, I now see the following error at deployment.

```shell
Resource handler returned message: "KnowledgeBase with name [MyKnowledgeBaseName11111111] already exists. Status Code: 409, Request ID: etc, etc.
```

### Expected Behavior

One should be able to deploy a stack as per usual.

### Current Behavior

```shell
Error: The stack named STACK_NAME failed to deploy: UPDATE_ROLLBACK_COMPLETE: Resource handler returned message: "KnowledgeBase with name MyKnowledgeBase111 already exists. (Service: BedrockAgent, Status Code: 409, Request ID: etc, etc.
```

### Reproduction Steps

A simple redeployment of the stack starts causing problems. The only thing I did was to upgrade the library.

### Possible Solution

Roll back the library version? I'll try that in the meantime.

### CDK CLI Version

2.156.0 (build 2966832)

### Framework Version

0.1.264

### Node.js Version

v22.8.0

### OS

MacOS Sonoma 14.6.1

### Language

Typescript

### Language Version

5.5.4

### Region experiencing the issue

us-west-2

### Code modification

No

### Service quota

- [X] I have reviewed the service quotas for this construct

**Comment by malikalimoekhamedov** [comment]
I ran the test and can certify the deployment goes through seamlessly with v0.1.262 of @cdklabs/generative-ai-cdk-constructs.

**Comment by aws-rafams** [comment]
Hi Malik, my hypothesis is that this is due to the [changes in the CloudFormation definition for Knowledge Bases](https://github.com/awslabs/generative-ai-cdk-constructs/issues/657) and thus CDK. Previously, when you created a knowledge base with the Titan embedding model, it used by default the embedding size of 1024. Now when you use Titan embeddings you should specify the embedding dimensions you want to use (1024, 512, or 256). Since the construct now defines this property, and CFN marks this property as [**Requires Replacement**](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-bedrock-knowledgebase-bedrockembeddingmodelconfiguration.html) is why it attempts to perform an update. This could be solved with a `addDeletionOverride` escape hatch. Will try to confirm my hypothesis and perform some tests. Will come back to you.

**Comment by aws-rafams** [comment]
Hi Malik, I confirm my hypothesis. After updating the library and performing a `cdk diff` you get:
![Screenshot 2024-09-12 at 10 36 42](https://github.com/user-attachments/assets/a367917a-cc95-4894-8e0d-2678c8fd9d4f)

**Comment by aws-rafams** [comment]
You can use the following escape hatch to solve the issue:
```ts
import * as cdk from 'aws-cdk-lib';
import { Construct } from 'constructs';
import * as opensearchserverless from '@cdklabs/generative-ai-cdk-constructs/lib/cdk-lib/opensearchserverless';
import { BedrockFoundationModel, KnowledgeBase } from '@cdklabs/generative-ai-cdk-constructs/lib/cdk-lib/bedrock';
import { CfnKnowledgeBase } from 'aws-cdk-lib/aws-bedrock';

export class TestIssue690Stack extends cdk.Stack {
  constructor(scope: Construct, id: string, props?: cdk.StackProps) {
    super(scope, id, props);

    const vectorStore = new opensearchserverless.VectorCollection(
      this,
      'VectorCollectionName',
      {
        collectionName: 'collection-name',
        standbyReplicas:
          process.env.ENV === 'prd'
            ? opensearchserverless.VectorCollectionStandbyReplicas.ENABLED
            : opensearchserverless.VectorCollectionStandbyReplicas.DISABLED,
      }
    );

    const kb = new KnowledgeBase(this, 'MyKnowledgeBaseName', {
      embeddingsModel: BedrockFoundationModel.TITAN_EMBED_TEXT_V2_1024,
      instruction: 'Some instructions.',
      description: 'Knowledge base description.',
      vectorStore,
    });

    // Backward compatibility hatch
    const cfnKbs = kb.node.findAll().filter((s) => s instanceof CfnKnowledgeBase) as CfnKnowledgeBase[]
    cfnKbs.forEach((cfnKb) => {
      cfnKb.addDeletionOverride("Properties.KnowledgeBaseConfiguration.VectorKnowledgeBaseConfiguration.EmbeddingModelConfiguration")
    })
  }
}
```

When adding the hatch, the `cdk diff` then becomes:
![Screenshot 2024-09-12 at 10 46 14](https://github.com/user-attachments/assets/78f09e6b-e751-40c5-b9ec-b0ebe78250b2)

**Comment by malikalimoekhamedov** [comment]
@aws-rafams, sorry to bother but the issue was reintroduced in version 0.1.170 again. I get the same error even with the backwards-compatibility hatch you described above.

```typescript
// Backward compatibility hatch
this.ref.node
  .findAll()
  .filter((s) => s instanceof CfnKnowledgeBase)
  .forEach((kb) =>
    kb.addDeletionOverride(
      'Properties.KnowledgeBaseConfiguration.VectorKnowledgeBaseConfiguration.EmbeddingModelConfiguration'
    )
  ); 
```

Perhaps you'd have a hunch?

**Comment by aws-rafams** [comment]
@malikalimoekhamedov Will take a look into it

**Comment by aws-rafams** [comment]
The only change I get from 0.1.264 to 0.1.270 is an IAM Policy statement update to adapt to the recommended structure ([link](https://docs.aws.amazon.com/bedrock/latest/userguide/kb-permissions.html#kb-permissions-trust)). This operation does not imply a replacement. Could you share your CDK diff? 

![Screenshot 2024-09-30 at 15 40 05](https://github.com/user-attachments/assets/87d8a110-1831-4949-b1ac-cb1af658b634)

**Comment by malikalimoekhamedov** [comment]
@aws-rafams, sorry for the delay. I ran a CDK diff with the latest version v0.1.171 and got the following output:

<img width="1013" alt="Screenshot 2024-10-02 at 13 32 39" src="https://github.com/user-attachments/assets/f14ed99e-b0d9-41a7-956b-87541f0962d3">

**Comment by malikalimoekhamedov** [comment]
Deployed well with the chunking strategy explicitly set. Thanks @aws-rafams for pointing me in the right direction.
