### ISSUE TITLE
(Bedrock): (Nova models incorrectly marked as not supporting cross-region inference)

### ISSUE THREAD

**Issue by s-maheshbabu** [awslabs/generative-ai-cdk-constructs#857]
### Describe the bug

As noted [here](https://us-east-2.console.aws.amazon.com/bedrock/home?region=us-east-2#/inference-profiles), Nova models support cross region inference. See image below.

However, the [code](https://github.com/awslabs/generative-ai-cdk-constructs/blob/910077113e947faff7d4dc1ad1429a7e033c36a9/src/cdk-lib/bedrock/models.ts#L87) is written to imply cross region inference is not supported. 

This results in the following error when trying to create an Agent with Nova models. 
`RuntimeError: Error: Model amazon.nova-pro-v1:0 does not support cross-region inference
`

<img width="1096" alt="image" src="https://github.com/user-attachments/assets/fefdeee8-c53b-48e9-a7ba-16afb4fd9043" />

### Expected Behavior

Nova models should be marked as supporting cross region inference.

### Current Behavior

Nova models are incorrectly marked as not supporting cross-region inference.

### Reproduction Steps

      agent = Agent(
          self,
          "Agent",
          foundation_model=CrossRegionInferenceProfile.from_config(
              geo_region=CrossRegionInferenceProfileRegion.US,
              model=BedrockFoundationModel.AMAZON_NOVA_PRO_V1,
          ),
          enable_user_input=True,
          instruction=INSTRUCTION,
          should_prepare_agent=True,
      )

### CDK CLI Version

2.160.0 (build 7a8ae02)

### Node.js Version

Node.js v20.5.1.

### OS

macOS Sequoia 15.0.1

### Language

Python

### Region experiencing the issue

us-east-2

### Code modification

No

### Service quota

- [X] I have reviewed the service quotas for this construct

**Comment by aws-rafams** [comment]
Hi @s-maheshbabu, you are correct, this is a bug and we will fix it ASAP.
